config/routes.rb
Rails.application.routes.draw do
  # get 'users/new'
  get 'pages/help'
  # get 'pages/index'
  root 'pages#index'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  # nameに空白制限をかける
  validates :name, length: { maximum:15}

  validates :email, presence: true
  # メールアドレスの正規表現を追加して下さい。
  validates :email, format: {with:/([a-zA-Z\d.])+@([a-zA-Z\d])+[.][(a-zA-Z0-9).]/i}
  # tuby05課題　パスワードの文字数制限
  validates :password, length: {minimum:8, maximum:23}
  # ruby05課題　パスワードをアルファベット、数字の混合
  validates :password, presence: true
  validates :password, format: {with:/([a-zA-Z\d])+/i}

  # available :password, numericality: fals

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # binding.pry
    # ↓Ruby04のセキュリティのところで変更する以前の形
    # @user = User.new(name: params[:user][:name], email: params[:user][:email])
    # 変更後
      @user = User.new(user_parmas)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger]="登録に失敗しました"
      render :new
    end
  end

  # Rails05のセキュリティのところ
  private
  def user_parmas
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert">
        <%= value %>
      </div>
      <% end %>

    <%= yield %>

    <!-- rails05 iQueryのところ -->
  <script>
    $(function(){
      $(".alert").fadeOut(5000);
    });
  </script>

  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです。</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Make you Happy</h1>
    <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign up', new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', '#',class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<!-- <h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p> -->

<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <!-- ruby05パスワ -->
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white'%>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          <%= f.submit "登録",class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら','#',class: 'text-white' %>
      </div>
    </div>
  </div>

</div>